#!/usr/bin/bash

rm -rf test test.o plain.o fast.o

# run gcc command and exit on error
run_gcc() {
    if ! gcc "$@"; then
        echo "Error in command: gcc $@" >&2
        exit 1
    fi
}

run_gcc -o test.o -c test.c -g -std=gnu11 -march=native # -O3
run_gcc -o plain.o -c plain.c -g -std=gnu11 -march=native # -O3
run_gcc -o fast.o -c fast.c -g -std=gnu11 -march=native # -O3
run_gcc plain.o fast.o test.o -o test -g -std=gnu11 -march=native # -O3

run_gcc plain.c -o plain.s -g -fverbose-asm -S -O3

./test
